// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go

// Package mocks_repository is a generated GoMock package.
package mocks_repository

import (
	model "cosmart/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// StoreBook mocks base method.
func (m *MockRepository) StoreBook(req model.Schedule) ([]model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBook", req)
	ret0, _ := ret[0].([]model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreBook indicates an expected call of StoreBook.
func (mr *MockRepositoryMockRecorder) StoreBook(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBook", reflect.TypeOf((*MockRepository)(nil).StoreBook), req)
}
